name: ESLint Check

on:
  push:
    branches:
      - '**'   # This will match all branches
    paths:
      - "force-app/**"
  
  pull_request:
    branches:
      - '**'   # This will match all branches
    paths:
      - "force-app/**"

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run ESLint
      run: npm run lint